{
 "title": "Dgraph",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(dgraph_memory_idle_bytes{instance=~'$Instance'}+dgraph_memory_inuse_bytes{instance=~'$Instance'})"
    }
   ]
  },
  {
   "title": "Zero and Alpha",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "dgraph_alpha_health_status{instance=~'$Instance'}-1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(dgraph_num_edges_total{instance=~'$Instance'})"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "go_goroutines{instance=~'$Instance'}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(dgraph_num_queries_total{instance=~'$Instance'})"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dgraph_memory_inuse_bytes+dgraph_memory_idle_bytes{instance=~'$Instance'}"
    },
    {
     "expr": "dgraph_memory_proc_bytes{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Active mutations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_active_mutations_total{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Pending Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_pending_proposals_total{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Memory Heap Idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dgraph_memory_idle_bytes{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Processed Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dgraph_num_queries_total" }
   ]
  },
  {
   "title": "GC second sum rate(30s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{instance=~'$Instance'}[30s])"
    }
   ]
  },
  {
   "title": "Pending Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_pending_queries_total{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Raft Applied Index",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_raft_applied_index{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Server Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_alpha_health_status{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "Last threads used by go.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_threads" }
   ]
  }
 ]
}